{% set name = "seamm-datastore" %}
{% set version = "2026.7.15" %}
{% set sha256 = "6412fa843d36a01f560a6ba89700a26b9adb1364b52a00e0f514a16468a7e725" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/s/seamm-datastore/seamm_datastore-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - flask
    - flask-authorize
    - marshmallow
    - marshmallow-sqlalchemy
    - python >={{ python_min }}
    - python-dateutil
    - six
    - sqlalchemy
    - werkzeug

test:
  imports:
    - seamm_datastore
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/molssi-seamm/seamm_datastore
  summary: A Python package for handling the SEAMM Dashboard database
  license: BSD-3-Clause
  license_file: LICENSE
  doc_url: https://molssi-seamm.github.io/seamm-datastore/

extra:
  recipe-maintainers:
    - paulsaxe
