{% set name = "seamm-datastore" %}
{% set version = "2024.6.2" %}
{% set sha256 = "d1eb0d0a1909b4670c3115c2bb82522a30e0302a525e23d1b97fca6632478492" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/seamm-datastore/seamm_datastore-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools
  run:
    - flask
    - flask-authorize
    - marshmallow
    - marshmallow-sqlalchemy
    - python >=3.8
    - python-dateutil
    - six
    - sqlalchemy
    - werkzeug

test:
  imports:
    - seamm_datastore
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/molssi-seamm/seamm_datastore
  summary: A Python package for handling the SEAMM Dashboard database
  license: BSD-3-Clause
  license_file: LICENSE
  doc_url: https://molssi-seamm.github.io/seamm-datastore/

extra:
  recipe-maintainers:
    - paulsaxe
